# REUSE licensing information association file
#
# References:
#
# * REUSE.toml | REUSE Specification – Version 3.2 | REUSE
#   https://reuse.software/spec-3.2/#reusetoml
#
# Copyright 2025 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0+

version = 1

[[annotations]]
path = [
    "speaker-photo.jpg",
    "motivation.png",
    "no-double-dots.png",
    "pangu-builtin.png",
    "*-screenshot.*",
    "package-image-search-results.png"
]
SPDX-FileCopyrightText = '2025 林博仁(Buo-ren Lin) <buo.ren.lin@gmail.com>'
SPDX-License-Identifier = 'CC-BY-SA-4.0+'

[[annotations]]
path = [
    "xkcd-927.jpg"
]
SPDX-FileCopyrightText = '2025 CQD, Randall Patrick Munroe, et. al. <https://xkcd.tw/927>'
SPDX-License-Identifier = 'CC-BY-NC-2.5'
